apps/bookshelf/urls.py
from django.urls import path
from . import views

app_name = "bookshelf"

urlpatterns = [
    path("", views.home, name="home"),
    # home api response
    # path("api/home/", views.home_api, name="home_api"),
    # example: /bookshelf/1/book/
    path("<int:book_id>/book/", views.book, name="book"),
    path("like", views.like_book, name="like_book"),
    # example: /bookshelf/api/1/book/
    # path("api/<int:book_id>/book/", views.book_api, name="book_api"),
    # example: /bookshelf/1/author/
    path("<int:author_id>/author/", views.author, name="author"),
    # example: /bookshelf/api/1/author/
    # path("api/<int:author_id>/author/", views.author_api, name="author_api"),
    # example: /bookshelf/1/user/
    path("<int:user_id>/user/", views.user, name="user"),
    # example: /bookshelf/api/1/user/
    # path("api/<int:user_id>/user/", views.user_api, name="user_api"),
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.registerPage, name="register"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
]

bookshelf/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.registerPage, name="register"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    
    path("", views.home, name="home"),
    # home api response
    path("api/home/", views.home_api, name="home_api"),
    # example: /bookshelf/1/book/
    path("<int:book_id>/book/", views.book, name="book"),
    # example: /bookshelf/api/1/book/
    path("api/<int:book_id>/book/", views.book_api, name="book_api"),
    # example: /bookshelf/1/author/
    path("<int:author_id>/author/", views.author, name="author"),
    # example: /bookshelf/api/1/author/
    path("api/<int:author_id>/author/", views.author_api, name="author_api"),
    # example: /bookshelf/1/user/
    path("<int:user_id>/user/", views.user, name="user"),
    # example: /bookshelf/api/1/user/
    path("api/<int:user_id>/user/", views.user_api, name="user_api"),
    # example: /bookshelf/1/add/
    path("<int:book_id>/add/", views.add_userbook, name="add_userbook"),
    # example: /bookshelf/1/remove/
    path("<int:book_id>/remove/", views.remove_userbook, name="remove_userbook"),
]

greatreads/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('bookshelf/', include('apps.bookshelf.urls')),
    path('', include('apps.users.urls')),
]

apps/bookshelf/models.py
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.CASCADE)
    published_at = models.DateField()
    isbn = models.CharField(max_length=13, null=True)
    image_url_s = models.URLField(null=True)
    image_url_m = models.URLField(null=True)
    image_url_l = models.URLField(null=True)
    liked = models.ManyToManyField(User, related_name="users_liked_books")
    def __str__(self):
        return self.title

        class Meta:
            ordering = ['title']

class Author(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class LikedBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="users_liked")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="books_liked")
    LIKE_CHOICES = (
        ('like', 'Like'),
        ('unlike', 'Unlike'),
    )
    value = models.CharField(choices=LIKE_CHOICES, max_length=10)
    def __str__(self):
        return f"{self.user} - {self.book}"

class UserBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(null=True)
    deleted_at = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.user} - {self.book}"

apps/users/models.py
from django.db import models

# Create your models here.

apps/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

apps/bookshelf/views.py
from .models import *
from .serializers import *
from rest_framework.decorators import api_view
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import MultipleObjectsReturned
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime
from django.http import JsonResponse
from django.db.models import F, Q

@login_required(login_url='users:login')
def home(request):
    books = Book.objects.all()
    authors = Author.objects.all()
    paginator = Paginator(books, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "books": books,
        "authors": authors,
        "page_obj": page_obj
    }
    return render(request, "bookshelf/home.html", context)

@login_required(login_url='users:login')
def book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    user = request.user
    userbook = UserBook.objects.filter(Q(user=user) & Q(book=book) & (Q(created_at__gt=F('deleted_at')) | Q(deleted_at__isnull=True)))
    if userbook:
        is_book_in_bookshelf = True
    else:
        is_book_in_bookshelf = False
    context = {
        "book": book,
        "is_book_in_bookshelf": is_book_in_bookshelf
    }
    return render(request, "bookshelf/book.html", context)

@login_required(login_url='users:login')
def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, "bookshelf/author.html", {"author": author})

@login_required(login_url='users:login')
def user(request, user_id):
    user = request.user
    # if book is liked by user then add to user page
    liked_books = Book.objects.filter(liked=user)
    context = {
        "user": user,
        "liked_books": liked_books
    }
    return render(request, "bookshelf/user.html", context)

def like_book(request):
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        book = get_object_or_404(Book, pk=book_id)
        user = request.user
        if user in book.liked.all():
            book.liked.remove(user)
            like_value = 'unlike'
        else:
            book.liked.add(user)
            like_value = 'like'
        
        like, created = LikedBook.objects.get_or_create(user=user, book=book)
        like.value = 'Unlike' if like.value == 'Like' else 'Like'
        like.save()

        # data = {'value': like.value}
        # return JsonResponse(data)
    return HttpResponseRedirect(reverse("bookshelf:book", args=(book_id,)))



# def user_api(request, user_id):
#     user = get_object_or_404(User, pk=user_id)
#     # user_books = UserBook.objects.filter(user=user)
#     serializer = UserSerializer(user)
#     return JsonResponse(serializer.data, safe=False)

# def author_api(request, author_id):
#     author = get_object_or_404(Author, pk=author_id)
#     serializer = AuthorSerializer(author)
#     return JsonResponse(serializer.data)

# def book_api(request, book_id):
#     book = get_object_or_404(Book, pk=book_id)
#     serializer = BookSerializer(book)
#     return JsonResponse({'book': serializer.data})

# @login_required(login_url='users:login')
# @api_view(['GET'])
# def home_api(request):
#     if request.method == 'GET':
#         books = Book.objects.all()
#         serializer = BookSerializer(books, many=True)
#         return JsonResponse({"books": serializer.data})

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreatUserForm()
        if request.method == 'POST':
            form = CreatUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('login')

        context = {'form': form}
        return render(request, 'register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username or password is incorrect.')

        context = {}
        return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('users:login')

bookshelf/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import MultipleObjectsReturned
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Book, Author, UserBook
from .forms import CreatUserForm
from datetime import datetime
from .serializers import *
from django.http import JsonResponse
from rest_framework.decorators import api_view

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreatUserForm()
        if request.method == 'POST':
            form = CreatUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('login')

        context = {'form': form}
        return render(request, 'bookshelf/register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username or password is incorrect.')

        context = {}
        return render(request, 'bookshelf/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def home(request):
    books = Book.objects.all()
    authors = Author.objects.all()
    context = {
        "books": books,
        "authors": authors
    }
    return render(request, "bookshelf/home.html", context)

@login_required(login_url='login')
@api_view(['GET'])
def home_api(request):
    if request.method == 'GET':
        books = Book.objects.all()
        serializer = BookSerializer(books, many=True)
        return JsonResponse({"books": serializer.data})

@login_required(login_url='login')
def book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, "bookshelf/book.html", {"book": book,})

def book_api(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    serializer = BookSerializer(book)
    return JsonResponse({'book': serializer.data})

@login_required(login_url='login')
def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, "bookshelf/author.html", {"author": author})

def author_api(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    serializer = AuthorSerializer(author)
    return JsonResponse(serializer.data)

def add_userbook(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    user = request.user
    try:
        userbook = UserBook.objects.get(book=book, user=user)
    except (KeyError, UserBook.DoesNotExist):
        u = UserBook(user=user, book=book, created_at=datetime.now())
        u.save()
        messages.success(request, book.title + ' was added to your bookshelf')
    except MultipleObjectsReturned:
        messages.error(request, "this book is already on your bookshelf")
    else:
        messages.error(request, "this book is already on your bookshelf")
    return HttpResponseRedirect(reverse("home"))

def remove_userbook(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    user = request.user
    try:
        userbook = UserBook.objects.get(book=book, user=user)
    except (KeyError, UserBook.DoesNotExist):
        messages.error(request, "this book is not on your bookshelf")
    else:
        userbook.deleted_at = datetime.now()
        userbook.save()
        messages.success(request, book.title + ' was removed from your bookshelf')
    return HttpResponseRedirect(reverse("home"))


@login_required(login_url='login')
def user(request, user_id):
    user = request.user
    user_books = UserBook.objects.filter(user=user)
    for user_book in user_books:
        if user_book.deleted_at is None:
            return user_book
        elif user_book.created_at > user_book.deleted_at:
            return userbook

    # user_books = user_books.filter(created_at__lte=user_books.deleted_at)
    # print("book id = ", user_books[0].book.id, "userbook user id = ", user_books[0].user.id, "userbook id = ", user_books[0].id, "request user id = ", user.id, "user id = ", user_id, user_books[0].created_at)
    context = {
        "user": user,
        "user_books": user_book
    }
    return render(request, "bookshelf/user.html", context)

def user_api(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # user_books = UserBook.objects.filter(user=user)
    serializer = UserSerializer(user)
    return JsonResponse(serializer.data, safe=False)

templates/bookshelf/author.html
{% extends 'main.html' %}

{% block content %}

<h2>Author</h2>

<h1>{{ author.first_name }} {{ author.last_name }}</h1>


{% endblock %}

templates/bookshelf/book.html
{% extends 'main.html' %}

{% block content %}

<h1>Book</h1>
<h2>{{ book.title }}</h2>
<img src="{{book.image_url_s}}" alt="">
<h2>Author: {{ book.author }}</h2>
<h3>Published: {{ book.published_at }}</h3>
<h3> {{ user.id }} {{ book.id }}</h3>
<h3>{{is_book_in_bookshelf}}</h3>
{% include 'bookshelf/like_button.html' %}

{% for message in messages %}
    <p id="messages">{{message}}</p>
{% endfor %}

{% endblock %}

templates/bookshelf/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <style>
        .movie {
            margin-bottom: 20px; /* Adjust the margin-bottom value to increase or decrease spacing */
        }
    </style>

    <header>
        <h1>Welcome to the Library, {{request.user}}. Why don't you click on a book and add it to your bookshelf by liking it!</h1>
    </header>

    <div class="container">
        <div class="gallery">
        {% if books %}
            {% for book in page_obj %}
                <div class="movie">
                    <img src={{book.image_url_s}} alt="Movie 1">
                    <div class="overlay">
                        <div class="overlay-content">
                            <a href="{% url 'bookshelf:book' book.id %}">
                                <h3>{{book.title}}</h3>
                            </a>
                        </div>
                    </div>
                    <a href="{% url 'bookshelf:author' book.author_id %}">
                        <h3>{{book.author}}</h3>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>No books are available.</p>
        {% endif %}
        </div>
    </div>

    <!-- <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> -->

</body>
</html>
{% include 'pagination.html' %}


{% endblock %}

templates/bookshelf/index.html
{% extends 'main.html' %}

{% block content %}

<h2>Library</h2>
{% if books %}
    <ul>
    {% for book in books %}
            <li>
                <a href="{% url 'book' book.id %}">{{ book.title }} - </a>
                <a href="{% url 'author' book.author_id %}">{{ book.author }}</a>
                <button type="button" class="btn btn-dark">Dark</button>
            </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}

{% endblock %}

templates/bookshelf/like_button.html
<form action="{% url 'bookshelf:like_book' %}" method="POST" class="like-form" id="{{book.id}}">
    {% csrf_token %}
    <input type="hidden" name="book_id" value="{{book.id}}" />
    <button type="submit" class="like-btn{{book.id}}">
        {% if user not in book.liked.all %}
        <span class="like-text{{book.id}} label-like-comment-share">Like?</span>
        {% else %}
        <span class="like-text{{book.id}} text-like_unlike-span label-like-comment-share">Unlike?</span>
        {% endif %}
    </button>
</form>

templates/bookshelf/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'users:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

templates/bookshelf/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                {{form.errors}}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

templates/bookshelf/user.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<style>
    .movie {
        margin-bottom: 20px; /* Adjust the margin-bottom value to increase or decrease spacing */
    }
</style>

<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <header>
        <h1>Welcome to your bookshelf, {{user}}</h1>
    </header>
    <div class="container">
        <div class="gallery">
        {% if liked_books %}
            {% for liked_book in liked_books %}
                <div class="movie">
                    <img src="{{liked_book.image_url_s}}" alt="Movie 1">
                    <div class="overlay">
                        <div class="overlay-content">
                            <a href="{% url 'bookshelf:book' liked_book.id %}">
                                <h3>{{liked_book.title}}</h3>
                            </a>
                        </div>
                    </div>
                    <a href="{% url 'bookshelf:author' liked_book.author.id %}">
                        <h3>{{liked_book.author}}</h3>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>No books added to bookshelf yet.</p>
        {% endif %}
        </div>
    </div>
</body>


{% endblock %}