apps/bookshelf/urls.py
from django.urls import path
from . import views

app_name = "bookshelf"

urlpatterns = [
    path("", views.home, name="home"),
    # home api response
    # path("api/home/", views.home_api, name="home_api"),
    # example: /bookshelf/1/book/
    path("<int:book_id>/book/", views.book, name="book"),
    path("like", views.like_book, name="like_book"),
    # example: /bookshelf/api/1/book/
    # path("api/<int:book_id>/book/", views.book_api, name="book_api"),
    # example: /bookshelf/1/author/
    path("<int:author_id>/author/", views.author, name="author"),
    # example: /bookshelf/api/1/author/
    # path("api/<int:author_id>/author/", views.author_api, name="author_api"),
    # example: /bookshelf/1/user/
    path("<int:user_id>/user/", views.user, name="user"),
    # example: /bookshelf/api/1/user/
    # path("api/<int:user_id>/user/", views.user_api, name="user_api"),
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.registerPage, name="register"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
]

bookshelf/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("register/", views.registerPage, name="register"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    
    path("", views.home, name="home"),
    # home api response
    path("api/home/", views.home_api, name="home_api"),
    # example: /bookshelf/1/book/
    path("<int:book_id>/book/", views.book, name="book"),
    # example: /bookshelf/api/1/book/
    path("api/<int:book_id>/book/", views.book_api, name="book_api"),
    # example: /bookshelf/1/author/
    path("<int:author_id>/author/", views.author, name="author"),
    # example: /bookshelf/api/1/author/
    path("api/<int:author_id>/author/", views.author_api, name="author_api"),
    # example: /bookshelf/1/user/
    path("<int:user_id>/user/", views.user, name="user"),
    # example: /bookshelf/api/1/user/
    path("api/<int:user_id>/user/", views.user_api, name="user_api"),
    # example: /bookshelf/1/add/
    path("<int:book_id>/add/", views.add_userbook, name="add_userbook"),
    # example: /bookshelf/1/remove/
    path("<int:book_id>/remove/", views.remove_userbook, name="remove_userbook"),
]

greatreads/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('bookshelf/', include('apps.bookshelf.urls')),
    path('', include('apps.users.urls')),
]

apps/users/models.py
from django.db import models

# Create your models here.

apps/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreatUserForm()
        if request.method == 'POST':
            form = CreatUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('login')

        context = {'form': form}
        return render(request, 'register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username or password is incorrect.')

        context = {}
        return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('users:login')

templates/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <style>
        .movie {
            margin-bottom: 20px; /* Adjust the margin-bottom value to increase or decrease spacing */
        }
    </style>

    <header>
        <h1>Welcome to the Bookshop, {{request.user}}</h1>
    </header>

    <div class="container">
        <div class="gallery">
        {% if books %}
            {% for book in page_obj %}
                <div class="movie">
                    <img src={{book.image_url_s}} alt="Movie 1">
                    <div class="overlay">
                        <div class="overlay-content">
                            <a href="{% url 'book' book.id %}">
                                <h3>{{book.title}}</h3>
                            </a>
                        </div>
                    </div>
                    <a href="{% url 'author' book.author_id %}">
                        <h3>{{book.author}}</h3>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>No books are available.</p>
        {% endif %}
        </div>
    </div>

    <!-- <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div> -->

</body>
</html>
{% include 'pagination.html' %}


{% endblock %}

templates/main.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>Greatreads</title>
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"> -->
        {% tailwind_css %}
    </head>
    <body>
        {% include 'navbar.html' %}
        <script src="{% static 'js/navbar.js' %}"></script>
        <hr>

        {% block content %}

        {% endblock %}

    </body>
</html>

templates/navbar.html
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'bookshelf:home' %}" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Library</a>
            <a href="{% url 'bookshelf:user' user.id %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">My Bookshelf</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <div>
            <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" id="menu">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign ooot</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <!-- <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2"> -->
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <!-- <a href="#" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Dashboard</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Team</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Projects</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Calendar</a>
    </div>
  </div> -->
</nav>

templates/pagination.html
<div class="flex items-center justify-between border-t border-gray-800 bg-gray-800 px-4 py-3 sm:px-6">
    <div class="flex flex-1 justify-between sm:hidden">
      <a href="#" class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-300 hover:bg-gray-50">Previous</a>
      <a href="#" class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-white hover:bg-gray-50">Next</a>
    </div>
    <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
      <div>
        <p class="text-sm text-white">
          Showing
          <span class="font-medium">{{ page_obj.number }}</span>
          of
          <span class="font-medium">{{ page_obj.paginator.num_pages }}</span>
          results
        </p>
      </div>
      <div>
        <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
          {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="relative inline-flex items-center rounded-l-md px-2 py-2 text-white ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                <span class="sr-only">Previous</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
                </svg>
            </a>
          {% endif %}
          <!-- Current: "z-10 bg-indigo-600 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", Default: "text-white ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:outline-offset-0" -->
          {% for i in page_obj.paginator.page_range %}
            <a href="?page={{ i }}" aria-current="page" class="relative {% if i == page_obj.number %} z-10 bg-indigo-600 text-white {% else %} inline-flex items-center text-gray-400 {% endif %} px-4 py-2 font-semibold ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">{{ i }}</a>
          {% endfor %}
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="relative inline-flex items-center rounded-r-md px-2 py-2 text-white ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
                <span class="sr-only">Next</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                </svg>
            </a>
          {% endif %}
        </nav>
      </div>
    </div>
</div>

templates/user.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<style>
    .movie {
        margin-bottom: 20px; /* Adjust the margin-bottom value to increase or decrease spacing */
    }
</style>

<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <header>
        <h1>Welcome to your personal bookshelf, {{user}}</h1>
    </header>
    <h3>{{ deleted_at }}</h3>
    <div class="container">
        <div class="gallery">
        {% if user_books %}
            {% for user_book in user_books %}
                <div class="movie">
                    <img src="{{user_book.book.image_url_s}}" alt="Movie 1">
                    <div class="overlay">
                        <div class="overlay-content">
                            <a href="{% url 'book' user_book.book.id %}">
                                <h3>{{user_book.book.title}}</h3>
                            </a>
                        </div>
                    </div>
                    <a href="{% url 'author' user_book.book.author.id %}">
                        <h3>{{user_book.book.author}}</h3>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>No books added to bookshelf yet.</p>
        {% endif %}
        </div>
    </div>
</body>


{% endblock %}